-- Injury seed data (auto-generated from Exercise database.xlsx)
-- Run once against the database

INSERT INTO Injury_Reference (name, body_part, common_causes) VALUES
  ('Hip Pain', 'Hip', 'Overuse, poor hip mechanics, weak glutes'),
  ('Ankle Sprain', 'Ankle', 'Rolling ankle inward during sports, uneven ground'),
  ('Knee Pain', 'Knee', 'Overuse, weak VMO'),
  ('Lower Back Pain', 'Lower Back', 'Poor posture, prolonged sitting'),
  ('Neck Pain', 'Neck', 'Poor posture, tech neck'),
  ('Thoracic Outlet Syndrome', 'Shoulder/Neck', 'Poor posture, heavy backpacks'),
  ('Carpal Tunnel Syndrome', 'Wrist', 'Typing, repetitive wrist motion'),
  ('Rotator Cuff Tear', 'Shoulder', 'Sports, lifting'),
  ('Wrist Pain', 'Wrist', 'Repetitive typing, weightlifting'),
  ('Elbow Pain', 'Elbow', 'Overuse, tennis'),
  ('Plantar Fasciitis', 'Foot', 'Running, standing long hours'),
  ('Sciatica', 'Lower Back', 'Poor posture, sitting long'),
  ('IT Band Syndrome', 'Thigh/Outer Knee', 'Running, cycling'),
  ('Hamstring Strain', 'Hamstring', 'Poor warm-up, sprinting'),
  ('Shin Splints', 'Lower Leg', 'Running, improper footwear'),
  ('AC Joint Injury', 'Shoulder', 'Fall on shoulder'),
  ('Patellar Tendonitis', 'Knee', 'Sports, jumping'),
  ('Groin Strain', 'Hip / Inner Thigh', 'Sports, sudden movements'),
  ('Scoliosis', 'Spine', 'Poor posture, genetics'),
  ('Tension Headache', 'Neck / Head', 'Stress, poor posture'),
  ('Frozen Shoulder', 'Shoulder', 'Post-surgery, immobilization'),
  ('Anterior Pelvic Tilt', 'Hips / Core', 'Weak glutes, tight hip flexors'),
  ('Flat Feet', 'Feet / Ankles', 'Weak arches'),
  ('Biceps Tendonitis', 'Shoulder / Arm', 'Overuse, strain'),
  ('Achilles Tendonitis', 'Lower Leg', 'Overuse, tight calves'),
  ('Costochondritis', 'Chest / Upper Body', 'Inflammation, strain'),
  ('Meniscus Tear', 'Knee', 'Post-surgery / strain'),
  ('Labral Tear (Hip)', 'Hip / Gluteus', 'Labral injury, weakness'),
  ('SI Joint Dysfunction', 'Lower Back/Glutes', 'Falling, sudden twist'),
  ('Piriformis Syndrome', 'Glutes/Piriformis', 'Sitting long periods'),
  ('Patellofemoral Pain Syndrome', 'Knee', 'Running, jumping'),
  ('Cervical Radiculopathy', 'Neck', 'Poor posture'),
  ('Tennis Elbow', 'Elbow', 'Repetitive'),
  ('Golfer’s Elbow', 'Elbow', 'Repetitive'),
  ('Hip Labral Tear', 'Hip', 'Running'),
  ('Lumbar Disc Herniation', 'Lower Back', 'Flexion injuries'),
  ('Radial Tunnel Syndrome', 'Forearm', 'Repetitive'),
  ('De Quervain’s Tenosynovitis', 'Wrist', 'Overuse'),
  ('Tibialis Posterior Tendinopathy', 'Ankle', 'Overpronation'),
  ('Cervicogenic Dizziness', 'Neck', 'Whiplash'),
  ('Subacromial Impingement', 'Shoulder', 'Overhead activity'),
  ('Snapping Hip Syndrome', 'Hip', 'Tight flexors'),
  ('Posterior Tibial Tendon Dysfunction', 'Ankle', 'Overpronation'),
  ('Tarsal Tunnel Syndrome', 'Ankle', 'Nerve entrapment'),
  ('Myofascial Pain Syndrome', 'Variable', 'Overuse'),
  ('Osteoarthritis (Knee)', 'Knee', 'Weak quads'),
  ('Osteoarthritis (Hip)', 'Hip', 'Weak glutes'),
  ('Cervical Spondylosis', 'Neck', 'Posture'),
  ('Lumbar Spondylosis', 'Lower Back', 'Stiffness'),
  ('Osgood-Schlatter Disease', 'Knee', 'Overuse'),
  ('Lumbar Stenosis', 'Lower Back', 'Stiffness'),
  ('Trochanteric Bursitis', 'Hip', 'Weak glutes'),
  ('Posterior Shoulder Tightness', 'Shoulder', 'Tight capsule'),
  ('Prepatellar Bursitis', 'Knee', 'Prolonged kneeling'),
  ('Sinus Tarsi Syndrome', 'Ankle', 'Overuse'),
  ('High Ankle Sprain (Syndesmotic Injury)', 'Ankle', 'External rotation injury'),
  ('Scapular Dyskinesis', 'Upper Back', 'Overuse, poor mechanics, repetitive loading'),
  ('Biceps Tendinopathy', 'Shoulder', 'Overuse, poor mechanics, repetitive loading'),
  ('AC Joint Sprain', 'Shoulder', 'Overuse, poor mechanics, repetitive loading'),
  ('Wrist Extensor Strain', 'Wrist', 'Overuse, poor mechanics, repetitive loading'),
  ('Neck Strain', 'Neck', 'Overuse, poor mechanics, repetitive loading'),
  ('Upper Trapezius Strain', 'Neck', 'Overuse, poor mechanics, repetitive loading'),
  ('Rotator Cuff Tendinopathy', 'Shoulder', 'Overuse, poor mechanics, repetitive loading'),
  ('Wrist Flexor Strain', 'Wrist', 'Overuse, poor mechanics, repetitive loading'),
  ('Labral Tear (SLAP)', 'Shoulder', 'Overuse, poor mechanics, repetitive loading'),
  ('Shoulder Impingement', 'Shoulder', 'Overuse, poor mechanics, repetitive loading'),
  ('UCL Elbow Strain', 'Elbow', 'Overuse, poor mechanics, repetitive loading'),
  ('Subacromial Bursitis', 'Shoulder', 'Repetitive strain, overload, poor posture'),
  ('Cervical Disc Strain', 'Neck', 'Repetitive strain, overload, poor posture'),
  ('Rhomboid Strain', 'Upper Back', 'Repetitive strain, overload, poor posture'),
  ('Rotator Cuff Tear (Partial)', 'Shoulder', 'Repetitive strain, overload, poor posture'),
  ('TFCC Injury', 'Wrist', 'Repetitive strain, overload, poor posture'),
  ('Triceps Tendinopathy', 'Elbow', 'Repetitive strain, overload, poor posture'),
  ('Thoracic Muscle Strain', 'Upper Back', 'Repetitive strain, overload, poor posture'),
  ('Elbow Hyperextension', 'Elbow', 'Repetitive strain, overload, poor posture'),
  ('Cervical Facet Irritation', 'Neck', 'Repetitive strain, overload, poor posture'),
  ('Scapular Winging', 'Upper Back', 'Repetitive strain, overload, poor posture'),
  ('Hand Flexor Strain', 'Wrist', 'Repetitive strain, overload, poor posture')
ON DUPLICATE KEY UPDATE body_part = VALUES(body_part);
