-- Muscle group seed (auto-generated from Exercise database.xlsx)
INSERT INTO muscle_group (name) VALUES
  ('Gluteus Maximus'),
  ('Hamstrings'),
  ('Erector Spinae'),
  ('Core'),
  ('Gluteus Medius'),
  ('Quadriceps'),
  ('Iliopsoas'),
  ('Rectus Femoris'),
  ('Sartorius'),
  ('Pectineus'),
  ('TFL'),
  ('Glute Max (opposing)'),
  ('Piriformis'),
  ('Gluteus Max'),
  ('Tensor Fasciae Latae'),
  ('Core stabilizers'),
  ('Glute Medius'),
  ('Glutes (opposing)'),
  ('Glute Max'),
  ('Quads'),
  ('Hams'),
  ('Gluteus Minimus'),
  ('Glute Minimus'),
  ('Tibialis Anterior'),
  ('Peroneals'),
  ('Gastrocnemius'),
  ('Peroneus Longus/Brevis'),
  ('Soleus'),
  ('Intrinsic foot muscles'),
  ('Extensor Digitorum Longus'),
  ('Gastrocnemius (eccentric)'),
  ('Tibialis Posterior'),
  ('Foot intrinsics'),
  ('Intrinsic foot flexors'),
  ('Flexor Digitorum Longus'),
  ('Toe flexors'),
  ('Ankle stabilizers'),
  ('Full ankle stabilizers'),
  ('peroneals'),
  ('tibialis muscles'),
  ('Intrinsics'),
  ('Quadriceps (VMO)'),
  ('Vastus Lateralis'),
  ('Vastus Intermedius'),
  ('Hamstrings (stabilizers)'),
  ('Glutes'),
  ('IT Band'),
  ('Calves'),
  ('Quadriceps (Rectus Femoris)'),
  ('Vastus Medialis'),
  ('Quadriceps group'),
  ('Abdominals'),
  ('Abs'),
  ('Transverse Abdominis'),
  ('Obliques'),
  ('Hip Flexors'),
  ('Spine'),
  ('Hip flexors'),
  ('Back'),
  ('Lower Back'),
  ('Deep Neck Flexors'),
  ('Sternocleidomastoid'),
  ('Trapezius'),
  ('Neck flexors'),
  ('Traps'),
  ('SCM'),
  ('Upper Trapezius'),
  ('Levator Scapulae'),
  ('Neck muscles'),
  ('Neck'),
  ('Shoulder'),
  ('Suboccipitals'),
  ('Neck extensors'),
  ('Trapezius Rhomboids'),
  ('Posterior Deltoid'),
  ('Upper Back'),
  ('Neck Flexors'),
  ('Scalenes'),
  ('Neck/Shoulders'),
  ('Pectoralis Major'),
  ('Anterior Deltoid'),
  ('Chest/Shoulders'),
  ('Shoulders'),
  ('Rhomboids'),
  ('Spinal Extensors'),
  ('Latissimus Dorsi'),
  ('Teres Major'),
  ('Back / Shoulder'),
  ('Shoulders / Upper Back'),
  ('Forearm Flexors'),
  ('Fingers'),
  ('Wrist/Hand'),
  ('Forearm Extensors'),
  ('Hand Muscles'),
  ('Forearm Flexors/Extensors'),
  ('Wrist/Forearm'),
  ('Forearm Rotators'),
  ('Extensors of Fingers'),
  ('Forearm'),
  ('Extensors & Fingers'),
  ('Forearm Flexors & Extensors'),
  ('Wrist'),
  ('Thenar Muscles'),
  ('Finger Muscles'),
  ('Hand'),
  ('Infraspinatus'),
  ('Teres Minor'),
  ('Subscapularis'),
  ('Supraspinatus'),
  ('Deltoid'),
  ('Rotator Cuff'),
  ('Forearm & Hand'),
  ('Triceps'),
  ('Biceps'),
  ('Elbow'),
  ('Biceps/Triceps'),
  ('Arm'),
  ('Forearm Flexors/Biceps'),
  ('Foot Intrinsics'),
  ('Plantar Fascia'),
  ('Foot'),
  ('Lower Leg'),
  ('Foot Arch Muscles'),
  ('Calf'),
  ('Calf Muscles'),
  ('Toe Muscles'),
  ('Foot/Ankle Muscles'),
  ('Leg / Lower Back'),
  ('Hip Abductors'),
  ('Legs'),
  ('Hip Rotators'),
  ('Outer Thigh'),
  ('Posterior Chain'),
  ('Front Thigh'),
  ('Posterior Thigh'),
  ('Shin Muscles'),
  ('Ankle Muscles'),
  ('Foot Muscles'),
  ('Upper Back / Shoulder'),
  ('Deltoids'),
  ('Chest / Shoulder'),
  ('Thigh'),
  ('Adductors'),
  ('Inner Thigh'),
  ('Leg'),
  ('Spinal Erectors'),
  ('Back / Core'),
  ('Neck / Upper Back'),
  ('Neck / Shoulder'),
  ('Glutes / Lower Back'),
  ('Hip'),
  ('Rectus Abdominis'),
  ('Lower Abs'),
  ('Hips / Glutes'),
  ('Hips / Legs'),
  ('Intrinsic Foot Muscles'),
  ('Arch Muscles'),
  ('Foot / Ankle'),
  ('Ankle / Foot'),
  ('Calves / Foot'),
  ('Foot / Toes'),
  ('Biceps Brachii'),
  ('Brachialis'),
  ('Arm / Shoulder'),
  ('Brachioradialis'),
  ('Arm / Forearm'),
  ('Forearm / Shoulder'),
  ('Upper Back / Arm'),
  ('Calves / Achilles'),
  ('Posterior Tibialis'),
  ('Ankle / Achilles'),
  ('Calf / Foot'),
  ('Intercostals'),
  ('Chest'),
  ('Upper Back / Chest'),
  ('Shoulder / Chest'),
  ('Thigh / Knee'),
  ('Hips / Knee'),
  ('Glutes / Knee'),
  ('Glutes / Hip'),
  ('Hip / Glutes'),
  ('Knee Extensors'),
  ('Thigh Muscles'),
  ('Knee'),
  ('Deep cervical flexors'),
  ('upper traps'),
  ('Cervical stabilizers'),
  ('Upper trapezius'),
  ('Levator scapulae'),
  ('Scapular stabilizers'),
  ('Cervical extensors'),
  ('Neck stabilizers'),
  ('Neck & scap stabilizers'),
  ('Mid & lower traps'),
  ('Cervical extensors/flexors'),
  ('Thoracic spine'),
  ('Mid traps'),
  ('Pec major'),
  ('Ant deltoid'),
  ('Lower traps'),
  ('Extensor carpi radialis'),
  ('Forearm extensors'),
  ('Extensor group'),
  ('Wrist stabilizers'),
  ('Extensor digitorum'),
  ('Wrist extensors'),
  ('Pronator teres'),
  ('Supinator'),
  ('Flexor carpi radialis'),
  ('Pronator'),
  ('Wrist flexors'),
  ('Extensors'),
  ('Flexors'),
  ('Forearm flexors'),
  ('Flexor group'),
  ('Extensor'),
  ('Pronators'),
  ('Rectus femoris'),
  ('Hip stabilizers'),
  ('Glute medius'),
  ('Glute minimus'),
  ('Hip rotators'),
  ('Abductors'),
  ('Hip & spinal stabilizers'),
  ('Hip abductors'),
  ('Erector spinae'),
  ('Lumbar stabilizers'),
  ('Stabilizers'),
  ('Lumbar extensors'),
  ('Spinal'),
  ('Lower body'),
  ('Paraspinals'),
  ('Lats'),
  ('Posterior chain'),
  ('Flexor carpi'),
  ('Radial nerve'),
  ('Nerve path'),
  ('APL/EPB'),
  ('Thumb extensors'),
  ('Radial'),
  ('Ulnar'),
  ('APL'),
  ('Thumb'),
  ('Gastroc/soleus'),
  ('Tibialis posterior'),
  ('Foot stabilizers'),
  ('Plantar flexors'),
  ('Lower leg'),
  ('Ankle invertors'),
  ('Tibialis anterior'),
  ('Anterior chain'),
  ('Eye/vestibular'),
  ('Cervical rotators'),
  ('Cervical flexors'),
  ('Vestibular system'),
  ('Upper trap'),
  ('Rotator cuff'),
  ('Teres minor'),
  ('Posterior capsule'),
  ('Shoulder stabilizers'),
  ('Serratus anterior'),
  ('ITB'),
  ('Lateral hip'),
  ('Tibial nerve'),
  ('Ankle'),
  ('Deep neck flexors'),
  ('Rotators'),
  ('Balance muscles'),
  ('Oculomotor'),
  ('RC'),
  ('Pecs'),
  ('Anterior deltoid'),
  ('Serratus'),
  ('Trigger points'),
  ('Target region'),
  ('Supporting muscles'),
  ('Support'),
  ('Affected region'),
  ('Diaphragm'),
  ('Affected'),
  ('Target muscle'),
  ('Varies'),
  ('Fascia'),
  ('Target'),
  ('VMO'),
  ('Knee stabilizers'),
  ('Knee flexors'),
  ('Lower limb'),
  ('Gastroc'),
  ('Glute med'),
  ('Glute max'),
  ('Levator'),
  ('Upper back'),
  ('Cervicals'),
  ('Multifidi'),
  ('Spine stabilizers'),
  ('Lumbar'),
  ('Multifidus'),
  ('Lateral thigh'),
  ('Posterior deltoid'),
  ('Gastroc/Soleus'),
  ('Achilles tendon'),
  ('Gastrocs/ Soleus/ Plantar fascia (passive stretch)'),
  ('Peroneus longus & brevis'),
  ('intrinsic foot muscles'),
  ('Gluteus medius'),
  ('tibialis posterior'),
  ('Tib post'),
  ('soleus'),
  ('foot intrinsic muscle'),
  ('gluteus minimus'),
  ('Extensor Hallucis Longus'),
  ('foot intrinsics'),
  ('Peroneus Longus & Brevis'),
  ('Foot Intrinsic Muscles'),
  ('Extensor hallucis longus'),
  ('extensor digitorum longus'),
  ('ankle stabilizers'),
  ('Peroneus tertius'),
  ('Gastrocnemius & soleus'),
  ('Calf complex'),
  ('Lower leg stabilizers'),
  ('hip stabilizers'),
  ('Upper Back prime mover'),
  ('Upper body kinetic chain'),
  ('Shoulder prime mover'),
  ('Wrist prime mover'),
  ('Neck prime mover'),
  ('Elbow prime mover'),
  ('Shoulder primary muscle group'),
  ('Synergists and stabilizers'),
  ('Neck primary muscle group'),
  ('Upper Back primary muscle group'),
  ('Wrist primary muscle group'),
  ('Elbow primary muscle group'),
  ('Triceps Brachii'),
  ('Serratus Anterior'),
  ('Upper Pectoralis Major'),
  ('Lower Pectoralis Major'),
  ('Core Stabilizers'),
  ('Biceps Posterior Deltoid'),
  ('Forearms'),
  ('Rear Deltoid'),
  ('Triceps Long Head'),
  ('Deltoid (Anterior & Medial)'),
  ('Upper Traps'),
  ('Deltoid (Medial)'),
  ('Deltoid (Anterior)'),
  ('Deltoid (Medial/Posterior)'),
  ('Trapezius (Upper)'),
  ('Forearm Muscles'),
  ('Anconeus'),
  ('Deltoid (Stabilizer)'),
  ('Forearm Extensors/Flexors'),
  ('Deltoid (Posterior)'),
  ('Deltoid (Posterior & Medial)'),
  ('Deltoid Stabilizer'),
  ('None'),
  ('Knee Stabilizers'),
  ('Hip Stabilizers'),
  ('Hip Adductors'),
  ('Ankle Stabilizers'),
  ('Anterior Shin Muscles'),
  ('Calves (Isometric)'),
  ('Postural Muscles'),
  ('Quadriceps (emphasis)'),
  ('Core (stabilization)'),
  ('Quads only'),
  ('Glute Med'),
  ('Glute Min'),
  ('Hips'),
  ('Spinal Flexors'),
  ('External Oblique'),
  ('TVA'),
  ('Lower Rectus Abdominis'),
  ('Grip Muscles'),
  ('Core Muscles'),
  ('Upper Rectus Abdominis')
ON DUPLICATE KEY UPDATE name = VALUES(name);
